# Generated by Django 4.2.1 on 2023-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='holding_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordering_cost',
            field=models.FloatField(),
        ),
    ]
