# Generated by Django 4.2.1 on 2023-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_holding_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_delivery_time',
            field=models.FloatField(),
        ),
    ]
