# Generated by Django 4.2.1 on 2023-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_delivery_time',
            field=models.IntegerField(),
        ),
    ]
