# Generated by Django 4.2.1 on 2023-05-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_product_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_delivery_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rop',
            name='order_delivery_time',
            field=models.IntegerField(null=True),
        ),
    ]
