# Generated by Django 4.2.1 on 2023-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_product_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rop',
            name='order_delivery_time',
            field=models.DateField(null=True),
        ),
    ]
