# Generated by Django 4.2.1 on 2023-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_zeroproduct_inventory_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zeroproduct',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
