# Generated by Django 4.2.1 on 2023-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_2',
            field=models.BooleanField(null=True),
        ),
    ]
