# Generated by Django 4.2.1 on 2023-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_zeroproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zeroproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
